apiVersion: v1
kind: ConfigMap
data:
  KAFKA_URL: "udaconnect-kafka.default.svc:9092"
  KAFKA_TOPIC: "locations"
metadata:
  name: kafka-env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udaconnect-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udaconnect-zookeeper
  template:
    metadata:
      labels:
        app: udaconnect-zookeeper
    spec:
      containers:
      - name: zoo1
        image: confluentinc/cp-zookeeper:6.2.0
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
---
apiVersion: v1
kind: Service
metadata:
  name: udaconnect-zookeeper
  labels:
    app: udaconnect-zookeeper
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP  
  selector:
    app: udaconnect-zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udaconnect-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udaconnect-kafka
  template:
    metadata:
      labels:
        app: udaconnect-kafka
    spec:
      containers:
      - name: kafka1
        image: confluentinc/cp-kafka:6.2.0
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: udaconnect-zookeeper.default.svc:2181
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://udaconnect-kafka.default.svc:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: udaconnect-kafka
  labels:
    app: udaconnect-kafka
spec:
  ports:
  - name: client
    port: 9092
    protocol: TCP  
  selector:
    app: udaconnect-kafka