apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-location-producer
  name: udaconnect-location-producer
spec:
  ports:
  - name: "5000"
    port: 5005
    targetPort: 5005
    nodePort: 30004
  selector:
    service: udaconnect-location-producer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location-producer
  name: udaconnect-location-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location-producer
  template:
    metadata:
      labels:
        service: udaconnect-location-producer
    spec:
      containers:
      - image: leslieloo/nd064-udaconnect-location-producer:latest
        name: udaconnect-location-producer
        imagePullPolicy: Always
        env:        
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_TOPIC
      restartPolicy: Always
